sudo: required
language: c
before_install:
    - sudo apt-get update
install:
    - sudo apt-get install gcc-avr binutils-avr avr-libc
    - pip install --user cpp-coveralls
script:
    - make all

#This part is unavailable because of ongoing work on build/test system
#    - make avr
#    - make coverage
#after_success:
#    - make run
#    - cd test && coveralls --verbose --exclude test.c
#    - make clean
