sudo: required
language: c
before_install:
    - sudo apt-get update
install:
    - sudo apt-get install gcc-avr binutils-avr avr-libc
    - pip install --user cpp-coveralls
script:
    - make all
    - make avr
    - make check
after_success:
    - make run
    - cd test && coveralls --verbose --exclude test.*
    - make clean
