sudo: required
language: c
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install gcc-avr binutils-avr avr-libc valgrind
  - pip install --user cpp-coveralls
script:
  - make all
  - make -f makefile-coverage all
after_success:
  -  coveralls --verbose --exclude test/test.c
